
CREATE TABLE IF NOT EXISTS Links (
	ID INT(11) AUTO_INCREMENT NOT NULL,
	Uri VARCHAR(255) UNIQUE,
	CONSTRAINT PK_Links PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS ValuesToMain (
	ID INT(11) AUTO_INCREMENT NOT NULL,
	uriID INT(11) NOT NULL,
	htmlType VARCHAR(255) NOT NULL,
	repleaceContentWith VARCHAR(255),
	htmlSelector VARCHAR(255) NOT NULL,
	migrationTarget VARCHAR(255) NOT NULL,
	slopeID INT(11) NOT NULL,
	CONSTRAINT PK_ValueToMain PRIMARY KEY(ID),
	CONSTRAINT FK_ValueToMain_Links FOREIGN KEY(uriID) REFERENCES Links(ID)
);

CREATE TABLE IF NOT EXISTS ValuesToMain_Table (
	ID INT(11) AUTO_INCREMENT NOT NULL,
	masterValueID INT(11) NOT NULL,
	th_selector VARCHAR(255) NOT NULL,
	CONSTRAINT PK_ValueToMainTable PRIMARY KEY(ID),
	CONSTRAINT FK_ValueToMainTable_ValueToMain FOREIGN KEY(masterValueID)
	REFERENCES ValuesToMain(ID)
);

CREATE TABLE IF NOT EXISTS ValuesToMain_Table_Content(
	ID INT(11) AUTO_INCREMENT NOT NULL,
	th_ID INT(11) NOT NULL,
	statement VARCHAR(255) NOT NULL,
	replaceWith VARCHAR(255) NOT NULL,
	replaceMode VARCHAR(255) NOT NULL,
	CONSTRAINT PK_ValuesToMainTableContent PRIMARY KEY(ID),
	CONSTRAINT FK_ValuesToMainTableContent_ValuesToMain_Table FOREIGN KEY(th_ID)
	REFERENCES ValuesToMain_Table(ID)
);

CREATE TABLE IF NOT EXISTS Settings(
	ID INT(11) AUTO_INCREMENT NOT NULL,
	websitePassword VARCHAR(255) NOT NULL,
	interval INT(20),
	CONSTRAINT PK_Settings PRIMARY KEY(ID)
);

