
CREATE TABLE IF NOT EXISTS Links (
	ID INT(11) AUTO_INCREMENT NOT NULL,
	Uri VARCHAR(255) UNIQUE,
	CONSTRAINT PK_Links PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS ValuesToMain (
	ID INT(11) AUTO_INCREMENT NOT NULL,
	uriID INT(11) NOT NULL,
	htmlType VARCHAR(255) NOT NULL,
	repleaceContentWith VARCHAR(255),
	htmlSelector VARCHAR(255) NOT NULL,
	migrationTarget VARCHAR(255) NOT NULL,
	slopeID INT(11) NOT NULL,
	CONSTRAINT PK_ValueToMain PRIMARY KEY(ID),
	CONSTRAINT FK_ValueToMain_Links FOREIGN KEY(uriID) REFERENCES Links(ID)
);

CREATE TABLE IF NOT EXISTS ValuesToMain_Table (
	ID INT(11) AUTO_INCREMENT NOT NULL,
	masterID INT(11) NOT NULL,
	htmlSelectorIfExists VARCHAR(255),
	expectedValue VARCHAR(255) NOT NULL DEFAULT '',
	replaceWith VARCHAR(255) NOT NULL DEFAULT 'IMG',
	replacementType VARCHAR(255) NOT NULL DEFAULT 'INNER',
	customCSS VARCHAR(255),
	customAttributes VARCHAR(255),
	CONSTRAINT PK_Value_Table PRIMARY KEY(ID),
	CONSTRAINT FK_Table_Value FOREIGN KEY(masterID) REFERENCES ValuesToMain(ID)
);

CREATE TABLE IF NOT EXISTS Settings(
	ID INT(11) AUTO_INCREMENT NOT NULL,
	websitePassword VARCHAR(255) NOT NULL,
	intervalSpeed INT(11),
	CONSTRAINT PK_Settings PRIMARY KEY(ID)
);

